### ISSUE TITLE
Which paper does the code refer to?

### ISSUE THREAD

**Issue by briatte** [tslumley/regression-paper#1]
Dear @tslumley 

May I ask which paper I should read along the code, please? I could not find you in the table of contents of _Statistical Science_, but I might have looked at the wrong place.

Thanks in advance!

**Comment by tslumley** [comment]
It's not published yet, but you can get a preprint at Statistical Science near the bottom of this page: http://imstat.org/sts/future_papers.html

**Comment by briatte** [comment]
Thank you very much!
